### ISSUE TITLE
PyPi package broken in Python >= 3.9

### ISSUE THREAD

**Issue by pl4nty** [redpwn/rcds#166]
[The PyPi package](https://pypi.org/project/rcds/) hasn't been updated recently, so is missing 4a3af9ffc7ed2514274ae45d4cc0bc9dcc8e3a7a and throws the following fatal error in Python >= 3.9:
> TypeError: __init__() got an unexpected keyword argument 'encoding'

**Comment by ethanwu10** [comment]
[Published!](https://pypi.org/project/rcds/0.1.4/)
